telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    username: ${TELEGRAM_BOT_USERNAME:comfort_group_telega_bot}

server:
  port: 8181

onec:
  odata:
    base-url: ${ONEC_ODATA_BASE_URL:}
    username: ${ONEC_ODATA_USERNAME:}
    password: ${ONEC_ODATA_PASSWORD:}